module.exports.descriptors = [
    'Delicious',
    'Flavorful',
    'Tasty',
    'Appetizing',
    'mMouthwatering',
    'Inviting',
    'Divine',
    'Redwood',
    'Adorable',
    'Toothsome',
    'Delish',
    'Heavenly',
    'Dainty',
    'Pleasant',
    'Sweet',
    'Luscious',
    'Enjoyable',
    'Enticing'
]

module.exports.places = [
    'Cuisine',
    'candy shop',
    'Cafe',
    'Grill',
    'Italian Restaurant',
    'Japanese Restaurant',
    'Chocolate',
    'Thai Restaurant',
    'Donuts',
    'Lounge',
    'Bar',
    'Eatery',
    'Pizza',
    'Bakery',
    'Drive-In',
    'Dining',
    'Mexican Restaurant',
    'Drinks',
    'Chinese Restaurant',
    'Tea',
    'Kitchen'
]
